item {
	id: 1
	name: '5000'
}
item {
	id: 2
	name: '1000'
}
item {
	id: 3
	name: '500'
}
item {
	id: 4
	name: '100'
}
item {
	id: 5
	name: '50'
}
item {
	id: 6
	name: '20'
}
item {
	id: 7
	name: '10'
}