name: uvea
description: The mobile application for Uvea

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  camera: ^0.5.8+11
  rflutter_alert: ^1.0.3
  tflite: ^1.1.1
  path_provider: ^1.6.24
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/uveaLogo.png
    - assets/moneyModel/model_unquant.tflite
    - assets/moneyModel/labels.txt
    - assets/fdwModel/labels.txt
    - assets/fdwModel/model.tflite
    - assets/fdwModel/model_unquant.tflite